const itemCategories = {
    'Coupon/Card': 0,
    'Weapon': 2,
    'Shield': 8,
    'Hat': 3,
    'Jewel': 12,
    'Potion': 10,
    'Use/Item': 15,
    'Etc/Item': 14,
    'Pet': 13,
    'Accessory': 7,
    'Drill': 6,
    'ThrowingWeapon': 16,
    'Innerwear': 4,
    'Belt': 22,
    'Face': 25,
    'Over/Head': 24,
    'Ear': 17,
    'Tail': 18,
    'Shirt': 19,
    'Pants/Skirt': 20,
    'Hand': 26,
    'Socks': 27,
    'Shoes': 5,
    'Coat': 21,
    'Fashion Item': 23,
    'Recent': 999,
}

export { itemCategories }